### ISSUE TITLE
ReflectionFieldクラスのバグ修正

### ISSUE THREAD

**Issue by myConsciousness** [myConsciousness/reflection-test-helper#9]
# Bug Report

## 1. Bug Details

```java
    java.lang.IllegalStateException: java.lang.IllegalArgumentException: Can not set java.lang.String field org.thinkit.test.util.TestEntityForReflectionField.testField to java.lang.Class
        at org.thinkit.test.util.ReflectionField.setFieldValue(ReflectionField.java:65)
        at org.thinkit.test.util.ReflectionFieldTest.testWhenValueIsNotNull(ReflectionFieldTest.java:43)

        Caused by:
        java.lang.IllegalArgumentException: Can not set java.lang.String field org.thinkit.test.util.TestEntityForReflectionField.testField to java.lang.Class
            at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
            at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
            at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:58)
            at java.base/jdk.internal.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:75)
            at java.base/java.lang.reflect.Field.set(Field.java:793)
            at org.thinkit.test.util.ReflectionField.setFieldValue(ReflectionField.java:63)
            ... 1 more
```

## 2. What you did caused that bug

ユニットテストで `setFieldValue` を呼び出した際に発生。

## 3. How it should be

`setFieldValue` メソッドに実装ミスがある。
リフレクション処理を行っている箇所を調査する。

**Comment by myConsciousness** [comment]
#10 の内容で修正を行いコミット済みのため本件はクローズ。
